### ISSUE TITLE
Common errors when running BinDatasets

### ISSUE THREAD

**Issue by ZZZhuLF** [BlishLab/scriabin#11]
Just like another unresolved issue, I have also encountered this problem, whether using the example data or my own data. Comments regarding this issue have been ongoing from 2022 until recently, and everyone has faced the exact same problem. Please forgive me for submitting another issue to gain the attention of the author's team. This is because I am really eager to use Scriabin in my own research!

> ifnb <- BinDatasets(ifnb, split.by = "stim", dims = 1:30，coarse_cell_types = "coarse_ident", sigtest_cell_types = "seurat_annotations")

Setting optim_k.unique to 1.33
Binning with coarse cell types
Constructing neighbor graphs with reduction pca . . . 
Splitting object . . . 
Preparing integration . . . 
Generating anchorsets . . . 
Computing 2000 integration features
Scaling features for provided objects
Finding all pairwise anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 16193 anchors
Filtering anchors
	Retained 5133 anchors
Mapping anchor names . . . 
Generating anchor bins . . . 
Generating connectivity matrix . . . 
Optimizing number of bins . . . 
Error in if (check_completion(nbs_completion)) { : 
  the condition has length > 1

**Comment by ajwilk** [comment]
Hi there, responding in #7
